apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  chart:
    git: git@github.com:CarolineTeicher/operator/helm_playground
    path: charts/helloworld
    name: podinfo
    version: 3.2.0
  values:
    replicaCount: 2