apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: release
  namespace: default
spec:
  releaseName: "release"
  chart:
    git: git@github.com:carolineteicher/operator
    path: helm_playground/charts
    ref: master
  version: 3.2.0