apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  chart:
    git: git@github.com:CarolineTeicher/operator
    path: helm_playground/charts
    name: podinfo
    version: 3.2.0
  values:
    replicaCount: 3